# Generated by Django 5.0.6 on 2024-11-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loocal', '0002_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
