# Generated by Django 5.0.6 on 2024-11-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loocal', '0008_userprofile_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
