# Generated by Django 5.0.6 on 2024-11-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loocal', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
