# Generated by Django 5.0.6 on 2024-11-20 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='invitation_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='invitation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
