# Generated by Django 5.0.6 on 2024-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_status'),
        ('products', '0009_product_is_variable_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='product_variations',
            field=models.ManyToManyField(to='products.productvariation'),
        ),
    ]
