# Generated by Django 5.0.6 on 2024-11-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_custom_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='applicable_to_transport',
            field=models.BooleanField(default=False, verbose_name='Aplica al transporte'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_on_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de envio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
