# Generated by Django 5.0.6 on 2024-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_discount_applicable_to_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
