# Generated by Django 5.0.6 on 2024-11-27 00:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_company_name_order_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_preparation', 'En Preparación'), ('in_transit', 'En Tránsito'), ('delivered_paid', 'Entregada (Pagada)'), ('delivered_pending_payment', 'Entregada (Pendiente de Pago)'), ('canceled', 'Cancelada'), ('returned', 'Devuelta')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente de Pago'), ('in_progress', 'En Progreso'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending_preparation', 'Pendiente de Preparación'), ('preparing', 'Preparando para Envío'), ('ready_to_ship', 'Listo para Despacho'), ('in_transit', 'En Camino'), ('delivered', 'Entregado'), ('returned', 'Devuelto')], default='pending_preparation', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('field_changed', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
            ],
        ),
    ]
