# Generated by Django 5.0.6 on 2024-11-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_temporary',
            field=models.BooleanField(default=True),
        ),
    ]
