# Generated by Django 5.0.6 on 2024-05-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
