# Generated by Django 5.0.6 on 2024-06-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_attribute_category_cultivo_maduracion_origin_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='cultivo',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='maduracion',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='region',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Cultivo',
        ),
        migrations.DeleteModel(
            name='Maduracion',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
