# Generated by Django 5.0.6 on 2024-10-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productattributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
