# Generated by Django 5.0.6 on 2024-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_attribute_remove_product_price_attributeoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_variable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
