# Generated by Django 5.0.6 on 2024-10-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_variable_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variation_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
