# Generated by Django 5.0.6 on 2024-11-06 03:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariation_image_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='contenido_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('value', 'Value')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_on_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='unit_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unittype'),
        ),
    ]
